version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: account_manage_postgres
    restart: always
    environment:
      POSTGRES_DB: account_manage
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 129900
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - account-net

  adminer:
    image: adminer
    container_name: account_manage_adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - account-net
    depends_on:
      - postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: account_manage_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/account_manage
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 129900
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    networks:
      - account-net

volumes:
  postgres_data:

networks:
  account-net:
    driver: bridge
